### ISSUE TITLE
显示“暂时获取不到评论，点击重新载入评论”

### ISSUE THREAD

**Issue by DavidZhang53** [my19940202/wx-read-comment-extension#2]
![image](https://github.com/my19940202/wx-read-comment-extension/assets/49602757/e26902e3-cb7e-4111-822f-60fe24490b99)

**Comment by my19940202** [comment]
@DavidZhang53 我近期修复一下 到时候发布一下新版本

**Comment by my19940202** [comment]
@DavidZhang53 已经更新了  有空可以再去试用看看

**Comment by DavidZhang53** [comment]
> @DavidZhang53 已经更新了 有空可以再去试用看看

辛苦作者！

**Comment by my19940202** [comment]
@DavidZhang53 可以现在最新的zip包 重新安装，准备这几天上传到chrome edge的应用商店
如果有其他建议 也可以反馈我

**Comment by DavidZhang53** [comment]
> @DavidZhang53 可以现在最新的zip包 重新安装，准备这几天上传到chrome edge的应用商店 如果有其他建议 也可以反馈我

有个问题就是评论对应的句子找不到，看着有点累

**Comment by DavidZhang53** [comment]
> > @DavidZhang53 可以现在最新的zip包 重新安装，准备这几天上传到chrome edge的应用商店 如果有其他建议 也可以反馈我
> 
> 有个问题就是评论对应的句子找不到，看着有点累

现在可以找到了吗，那已经很完美了

**Comment by my19940202** [comment]
> > @DavidZhang53 可以现在最新的zip包 重新安装，准备这几天上传到chrome edge的应用商店 如果有其他建议 也可以反馈我
> 
> 有个问题就是评论对应的句子找不到，看着有点累

这个我抽空研究一下，目前微信读书页面的文本是canvas渲染的，对应原文还有点难度
应用商店上传完了 我再通知一下

**Comment by my19940202** [comment]
> > @DavidZhang53 可以现在最新的zip包 重新安装，准备这几天上传到chrome edge的应用商店 如果有其他建议 也可以反馈我
> 
> 有个问题就是评论对应的句子找不到，看着有点累

这个我抽空研究一下，目前微信读书页面的文本是canvas渲染的，对应原文还有点难度
应用商店上传完了 我再通知一下

**Comment by my19940202** [comment]
@DavidZhang53  上架到chrome应用商店了
https://chromewebstore.google.com/detail/%E5%BE%AE%E4%BF%A1%E8%AF%BB%E4%B9%A6%E8%AF%84%E8%AE%BA%E6%8F%92%E4%BB%B6/kfjimgaoegibikoojcbnkbffkongnoep
